services:
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # 1. Web-Interface & HTTPS
        external_url 'https://gitlab:4443'
        nginx['listen_port'] = 4443
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/certs/gitlab.crt"
        nginx['ssl_certificate_key'] = "/certs/gitlab.key"
        
        # 2. Container Registry (mit SSL)
        registry_external_url 'https://gitlab:5505'
        registry_nginx['listen_port'] = 5505
        registry_nginx['ssl_certificate'] = "/certs/gitlab.crt"
        registry_nginx['ssl_certificate_key'] = "/certs/gitlab.key"
        
        # 3. SSH (wichtig für die "Clone"-Links in der UI)
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        
        # 4 Let's Encrypt abschalten, da wir eigene Zertifikate nutzen
        letsencrypt['enable'] = false
    ports:
      - '8880:80'  # Web UI
      - '4443:4443'   # HTTPS - muss intern und extern denselben Port haben (Runner-Funktionalität)
      - '2222:22'    # SSH
      - '5505:5505'  # Container Registry
    volumes:
      - '${GITLAB_HOME:-${PWD}}/gitlab/config:/etc/gitlab'
      - '${GITLAB_HOME:-${PWD}}/gitlab/logs:/var/log/gitlab'
      - '${GITLAB_HOME:-${PWD}}/gitlab/data:/var/opt/gitlab'
      - '${GITLAB_HOME:-${PWD}}/shared/ssl:/certs:ro'
    networks:
      - gitlab-net
  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
    restart: always
    volumes:
      - '${GITLAB_HOME:-${PWD}}/runner/config:/etc/gitlab-runner'
      - '${GITLAB_HOME:-${PWD}}/shared/ssl:/etc/gitlab-runner/certs:ro'
      - '${GITLAB_HOME:-${PWD}}/runner/data:/var/opt/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - gitlab-net
networks:
  gitlab-net:
    name: gitlab-net